### ISSUE TITLE
Internal Error: Calculate hash value for sources in github repo

### ISSUE THREAD

**Issue by poscat0x04** [seppeljordan/nix-prefetch-github#38]
to reproduce:
```
> nix-prefetch-github arcticicestudio nord-dircolors
Internal Error: Calculate hash value for sources in github repo arcticicestudio/nord-dircolors.
```
versions:
```
nix (Nix) 2.4pre20201102_550e11f
nix-prefetch-github, version 4.0
```

**Comment by seppeljordan** [comment]
Hi, I identified the cause of the issue. The current implementation of `nix-prefetch-github` relies on the output of nix itself. This means that we try to fetch the github repo in question with a wrong sha256 intentionally to look for lines matching a certain pattern, e.g.
```
  specified: sha256-u42evoAl/P3/Ad6lcXgS1+dd2fcBwEqu4gNU/OjxlPg=
     got:    sha256-66Ynq+4sh59apqAEVeVLIAxkFgy96QSdpQjsLlsGoNo=
```
This is where `nix-prefetch-github` gets its hash sums from.

Since the output format of nix changed recently this package broke. I added the new output format to the source code and will release a fixed version to unstable in the near future.
